-- =============================================================================
-- Wissensbasis: Bestand einordnen (DATENAENDERUNG)
-- =============================================================================
-- Ordnet die 320 Bestandsdokumente (Einlese-Skript, alle aus Internetrecherchen) in Quellenart, Cluster und Stufe ein. Die Einordnung
-- stammt aus einer Durchsicht aller Dokumente (Link, bisherige Stufe, Titel, Pfad, Konfidenz) und steht hier je Dokument offen.
-- Die Administration kann sie danach jederzeit in der Seite Wissensbasis nachprüfen; eine falsche Einordnung korrigiert eine neue Migration
-- oder (für ein einzelnes Dokument) die Wissensbasis-Verwaltung.
--
-- Regeln:
--   * Cluster: immer "internet" (alle Dokumente stammen aus Internetrecherchen).
--   * Die Stufe folgt der Quellenart (src/lib/wissen/quellenart.ts, standardStufe), wie bei jedem Upload.
--   * Bisherige Stufe 1 = Gesetzestext: rechtsnorm. Ausnahmen: Auskünfte und Erklärungen von Behörden und internationalen Organisationen
--     (behoerdeninfo), das Statut einer Behörde (verwaltungsanweisung), die Darstellung einer Nichtregierungsorganisation (praxisbeitrag).
--   * Bisherige Stufe 3 = Seite einer Behörde: behoerdeninfo. Bisherige Stufe 5 = Bewertungsportal oder Forum: forum, Blog oder Erfahrungsbericht:
--     internetquelle (Notbehelf, wird dem Nutzer als ungesicherte Internetquelle gekennzeichnet).
--   * Bisherige Stufe 4: die Herkunft entscheidet. Normungsorganisationen: standard. Amtliche Rechtsquellen: rechtsnorm oder
--     verwaltungsanweisung. Amtliche Seiten: behoerdeninfo. Beratungen, Fachportale und internationale Organisationen: praxisbeitrag.
--     Presse, Rechner und Katalogseiten: internetquelle. Gesetzesauszüge von Spiegelportalen (kodeksy-kz.com, pavlodar.com ...):
--     fachliteratur, weil der Stand nicht amtlich bestätigt ist. Wissenschaftliche und sonstige Fachquellen: fachliteratur.
--   * Arbeitsdokumente der Recherche (Aufträge, Indizes, Pläne), Rohbefunde, KI-gestützte Literaturübersichten und Aussagen, die die Recherche
--     selbst als nicht verifizierbar nennt: internetrecherche (nur als Notbehelf, nie tragend). Diese Dokumente sind Kandidaten zum Entfernen
--     (docs/bestand-analyse-2026-10-09.md); entfernt wird hier nichts.
--   * Handelsketten-Standards (IFS, SQF, FSSC 22000, GFSI, Tesco, Costco, ISSAI): standard.
--
-- Nur Zeilen ohne Quellenart, die nicht aus dem Upload stammen. Wiederholbar: Eine zweite Ausführung findet nichts mehr. Eine bereits
-- eingeordnete Zeile (zum Beispiel über die Verwaltung) wird nie überschrieben. Prüfstatus, Rollen und Wiedervorlage bleiben unberührt, der
-- Wächter (wissen_pruefung_wache) greift nicht. Wirkung auf die Suche: Die Stufe folgt der Art, und Art und Bereich bestimmen die Nutzung.
-- Verteilung: rechtsnorm 44, verwaltungsanweisung 5, behoerdeninfo 31, standard 18, fachliteratur 79, praxisbeitrag 78, internetquelle 31, forum 5, internetrecherche 29.
-- Der Dateiname endet auf _pgvector.sql: wissen_chunks gibt es in PGlite nicht, die schnellen Tests überspringen ihn.
-- =============================================================================

set search_path = public;

update public.wissen_chunks c
   set quellenart = v.art,
       cluster = coalesce(c.cluster, 'internet'),
       autoritaetsstufe = v.stufe
  from (values
    ('adilet-nk-214-viii-ru', 'rechtsnorm', 1::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/saatgutgesetz.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/saatgut-sortenrecht/gesetz-ueber-saatgutwesen-385-ii-2003.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/bodenrecht-agrarland/adilet-bodengesetzbuch-artikel-24-verbot-fremdbeteiligung.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/agrarrecht-allgemein/gesetz-66-iii-2005-artikel-11-subventionierung-apk.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/investitionsrecht-zoll/unternehmerkodex-artikel-287-zollbefreiung.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/investitionsrecht-zoll/steuerkodex-artikel-399-einfuhrumsatzsteuerbefreiung.md', 'rechtsnorm', 1::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/statistikgesetz-meldepflicht-agrar.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/arbeitsrecht/eaeu-vertrag-artikel-97-arbeitnehmerfreizuegigkeit.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/eawu-aussenhandel/epca-eu-kasachstan-partnerschaftsabkommen-2016.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/gesellschaftsrecht-registrierung/gesetz-ueber-too-mindestkapital-artikel-23-24.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/arbeitsrecht/regierungsbeschluss-1041-2023-120-tage-geschaeftsreise.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/devisenrecht/devisenregulierungsgesetz-2018-registrierung-meldepflicht.md', 'rechtsnorm', 1::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/landverbot-2021-gesetz-permanent.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/bodenrecht-agrarland/zemelny-kodeks-artikel-24-verbot-agrarlandbesitz-auslaender.md', 'rechtsnorm', 1::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/pflanzenquarantaenegesetz.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/gesellschaftsrecht-registrierung/zivilgesetzbuch-artikel-58-hozyaystvennoe-tovarishchestvo.md', 'rechtsnorm', 1::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/veterinaergesetz.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/devisenrecht/gesetz-167-vi-devisenregulierung-grundlagen.md', 'rechtsnorm', 1::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/gesetz-304i-art5-investitionsvertrag-pflichtpruefung.md', 'rechtsnorm', 1::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/getreidegesetz.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/investitionsrecht-zoll/unternehmerkodex-artikel-283-investitionspraeferenzen.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/umweltrecht/gesetz-331-ii-artikel-14-6-registrierung-pestizide.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/wasserrecht/wasserkodex-178-viii-2025-inkrafttreten.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/datenschutzrecht/gesetz-94-v-artikel-12-lokalisierungspflicht.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/antikorruption/strafgesetzbuch-artikel-253-kommerzielle-bestechung.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/devisenrecht/verordnung-78-2023-uchetnaya-registratsiya-50000.md', 'rechtsnorm', 1::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/moratorium-2016-praesidialerlass-248.md', 'rechtsnorm', 1::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/informatisierungsgesetz-it-audit-regeln.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/saatgut-sortenrecht/gesetz-385-ii-saatgutgesetz-artikel-19-import.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/saatgut-sortenrecht/gesetz-schutz-selektionsleistungen-422-i-1999.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/steuerrecht-schnittstelle/steuergesetzbuch-2026-artikel-226-231-betriebsstaette.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/datenschutzrecht/gesetz-94-v-artikel-16-grenzueberschreitende-uebermittlung.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/pflanzenschutz-lebensmittelsicherheit/gesetz-ueber-pflanzenquarantaene-344-i-1999.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/geistiges-eigentum/urheberrechtsgesetz-6-i-software-als-literarisches-werk.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/arbeitsrecht/sozialkodex-224-vii-abloesung-beschaeftigungsgesetz.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/pflanzenschutz-lebensmittelsicherheit/gesetz-ueber-den-schutz-von-pflanzen-331-ii-2002.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/datenschutzrecht/gesetz-94-v-personenbezogene-daten-lokalisierung-und-transfer.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/umweltrecht/oekologischer-kodex-400-vi-artikel-12-vier-kategorien.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/wasserrecht/wodny-kodeks-178-viii-2025-artikel-17-wassernutzung.md', 'rechtsnorm', 1::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/verrechnungspreisgesetz-67iv.md', 'rechtsnorm', 1::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/ki-gesetz-230-viii-hochrisiko-audit.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/geistiges-eigentum/patentgesetz-427-i-patentfaehigkeit-software-ausschluss.md', 'rechtsnorm', 1::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/streitbeilegung-investitionsschutz/new-yorker-uebereinkommen-1958-kasachstan-beitritt-1996.md', 'rechtsnorm', 1::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/investitionspraeferenzen-prioritaetenliste-agrar.md', 'verwaltungsanweisung', 2::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/inspektionskomitee-agrarindustriekomplex-statut.md', 'verwaltungsanweisung', 2::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/vorlaeuferprogramme-apk-konzept.md', 'verwaltungsanweisung', 2::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/kartellrecht/azrk-agentur-schutz-entwicklung-wettbewerb-rechtsgrundlage.md', 'verwaltungsanweisung', 2::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/agrarrecht-allgemein/primeminister-kz-foerdersaetze-gewaechshaus-bewaesserung.md', 'verwaltungsanweisung', 2::smallint),
    ('kgd-api-interfeys-hub-section', 'behoerdeninfo', 3::smallint),
    ('iris-kz-kgd-blog-agent-nds-rus', 'behoerdeninfo', 3::smallint),
    ('kgd-nsi-tnved-klassifikator-rus', 'behoerdeninfo', 3::smallint),
    ('qaztrade-org-kz-exportfoerderung-rus', 'behoerdeninfo', 3::smallint),
    ('kgd-sur-anwendungsbereiche-offiziell', 'behoerdeninfo', 3::smallint),
    ('bns-stat-gov-kz-portal', 'behoerdeninfo', 3::smallint),
    ('kgd-astana1-faq-verbindung-rus', 'behoerdeninfo', 3::smallint),
    ('kgd-sko-snr-khfh-rus-veraltet', 'behoerdeninfo', 3::smallint),
    ('kgd-eservices-katalog-rus', 'behoerdeninfo', 3::smallint),
    ('kgd-vko-snr-kfh-rus', 'behoerdeninfo', 3::smallint),
    ('kgd-kommentar-nk-rk-online', 'behoerdeninfo', 3::smallint),
    ('kgd-esf-api-interface-rus', 'behoerdeninfo', 3::smallint),
    ('kgd-abai-kontosperre-altkodex-veraltet', 'behoerdeninfo', 3::smallint),
    ('kgd-api-integration-hub-rus', 'behoerdeninfo', 3::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/steuerrecht-schnittstelle/kgd-faq-betriebsstaette-praezedenzfall.md', 'behoerdeninfo', 3::smallint),
    ('kgd-esf-api-auth-gost2015-pressemitteilung', 'behoerdeninfo', 3::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/eawu-aussenhandel/wto-beitrittsprotokoll-kasachstan-2015.md', 'behoerdeninfo', 3::smallint),
    ('bns-agrarstatistik-formulare-29sch-49sch', 'behoerdeninfo', 3::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/wasserrecht/gov-kz-ministerium-wasserressourcen-digitalisierung.md', 'behoerdeninfo', 3::smallint),
    ('kgd-api-esf-virtualsklad-anleitung', 'behoerdeninfo', 3::smallint),
    ('qaztrade-order314-kostenerstattung-detail-rus', 'behoerdeninfo', 3::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/antikorruption/kasachstan-erklaerung-merida-unterzeichnungskonferenz-2003.md', 'behoerdeninfo', 3::smallint),
    ('kgd-astana1-systempage-rus', 'behoerdeninfo', 3::smallint),
    ('enpf-opvr-satz-erhoehung-2026', 'behoerdeninfo', 3::smallint),
    ('kgd-fno-uebersicht-2026', 'behoerdeninfo', 3::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/hoechste-auditkammer-abgrenzung.md', 'behoerdeninfo', 3::smallint),
    ('aifc-tax-benefits-offiziell', 'behoerdeninfo', 3::smallint),
    ('kazakhexport-kz-versicherung-rus', 'behoerdeninfo', 3::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/kazagro-baiterek-integration.md', 'behoerdeninfo', 3::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/staatliche-audit-datenbank-hoechste-auditkammer.md', 'behoerdeninfo', 3::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/baiterek-holding-kodex.md', 'behoerdeninfo', 3::smallint),
    ('audit/Audit/03-handelsketten-und-lieferantenaudits/D7-034_IFS_Food_Standard_Version_8.md', 'standard', 3::smallint),
    ('audit/Audit/03-handelsketten-und-lieferantenaudits/D7-030_Tesco_Nurture_Module_Scheme_Rules_Version_12_0.md', 'standard', 3::smallint),
    ('audit/Audit/damicon-audit-kb-grundlagen/quellen/coso-internal-control-framework-2013.md', 'standard', 3::smallint),
    ('audit/Audit/03-handelsketten-und-lieferantenaudits/D7-037_SQF_Code_Edition_9.md', 'standard', 3::smallint),
    ('audit/Audit/03-handelsketten-und-lieferantenaudits/D7-038_FSSC_22000_Scheme_Version_6_0.md', 'standard', 3::smallint),
    ('audit/Audit/03-handelsketten-und-lieferantenaudits/D7-031_GFSI_Benchmarking_Requirements_Version_2024_Process_Handbook_Part_I_Implementati.md', 'standard', 3::smallint),
    ('audit/Audit/01-interne-revision-und-oeffentlicher-sektor/D2-031_ISSAI_140_Quality_Management_for_SAIs_revidierte_Fassung.md', 'standard', 3::smallint),
    ('audit/Audit/03-handelsketten-und-lieferantenaudits/D7-029_Costco_Food_Safety_Audit_Expectations_unangekündigte_Audits_Costco_Addendum.md', 'standard', 3::smallint),
    ('audit/Audit/03-handelsketten-und-lieferantenaudits/D7-033_GFSI-Recognised_Certification_Programme_Owners_Übersichtsliste.md', 'standard', 3::smallint),
    ('audit/Audit/damicon-audit-kb-grundlagen/quellen/diir-uebersetzung-three-lines-model.md', 'standard', 3::smallint),
    ('audit/Audit/damicon-audit-kb-grundlagen/quellen/iia-three-lines-model-2020.md', 'standard', 3::smallint),
    ('audit/Audit/damicon-audit-kb-grundlagen/quellen/iaasb-technology-quality-management-initiative.md', 'standard', 3::smallint),
    ('audit/Audit/damicon-audit-kb-grundlagen/quellen/oecd-beps-action13-verrechnungspreise.md', 'standard', 3::smallint),
    ('audit/Audit/damicon-audit-kb-grundlagen/quellen/iia-global-internal-audit-standards-2025.md', 'standard', 3::smallint),
    ('audit/Audit/damicon-audit-kb-grundlagen/quellen/coso-erm-framework-2017.md', 'standard', 3::smallint),
    ('audit/Audit/damicon-audit-kb-grundlagen/quellen/iso-31000-2018-risikomanagement.md', 'standard', 3::smallint),
    ('audit/Audit/damicon-audit-kb-grundlagen/quellen/iso-19011-2026-auditierung-managementsysteme.md', 'standard', 3::smallint),
    ('audit/Audit/damicon-audit-kb-grundlagen/quellen/iaasb-att-guidance-2020-2021.md', 'standard', 3::smallint),
    ('kodeksy-kz-nk-518-530-eaeu-import-nds-rus', 'fachliteratur', 4::smallint),
    ('kodeksy-kz-nk-125-128-nds-erstattung-export-rus', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/ip-und-datenschutz-grundlagen/dsgvo-auftragsverarbeitung-artikel-28.md', 'fachliteratur', 4::smallint),
    ('cyberleninka-nazarbekov-tsifra-selhoz-kz-2023', 'fachliteratur', 4::smallint),
    ('kodeksy-kz-nk-479-import-nds-befreiung-rus', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/bodenrecht-agrarland/agrardialog-kaz-berkmalov-zemelny-kodeks-2017.md', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/umweltrecht/iea-policy-datenbank-umweltgesetzbuch-bat.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/datenschutz-ki-grenzueberschreitend.md', 'fachliteratur', 4::smallint),
    ('cyberleninka-zaurbekova-gospodderzhka-selhoz-eaes-vto-2019', 'fachliteratur', 4::smallint),
    ('kodeksy-kz-gk-mirror-rus', 'fachliteratur', 4::smallint),
    ('kgd-astana1-hintergrund-asycuda-rus', 'fachliteratur', 4::smallint),
    ('kodeksy-kz-nk-mirror-rus', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/rechnungslegungsgesetz-234-iii.md', 'fachliteratur', 4::smallint),
    ('jpra-shulenbaeva-zemli-selhoz-kz-2025', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/datenschutzrecht/greenleaf-kaldani-datenschutzrecht-zentralasien-studie.md', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/ip-und-datenschutz-grundlagen/dsgvo-grundprinzipien-artikel-5.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/subventionsregeln-uebersicht-ministererlasse.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/bankengesetz-risikomanagement.md', 'fachliteratur', 4::smallint),
    ('kodeksy-kz-nk-134-import-nds-stundung-rus', 'fachliteratur', 4::smallint),
    ('tkeaes-ru-zollwert-berechnung-stundung-rus', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-grundlagen/quellen/xai-explainable-ai-auditing-literatur.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/wissenschaftliche-literatur-ki-staatsaudit-kasachstan.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/typovoy-kodeks-staatliche-ag.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/rechtsform-kfh-unternehmerkodex-art41.md', 'fachliteratur', 4::smallint),
    ('apa-shatenova-fiskal-dezentralisierung-2025', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/agrarrecht-allgemein/gosagro-antragsverfahren-subventionen.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/landkodex-art92-zwangsentzug.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/rechnungshofkritik-baiterek-2020.md', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/eawu-aussenhandel/apfelimportverbot-eawu-freier-warenverkehr-konflikt.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/marktdaten-pruefungsdienstleistungsmarkt.md', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/saatgut-sortenrecht/inform-kz-beerensorten-lizenzierung.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-grundlagen/quellen/techtarget-coso-iso31000-vergleich.md', 'fachliteratur', 4::smallint),
    ('pavlodar-mirror-nk-st357-rus', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/vertragsrecht-grundlagen/cisg-un-kaufrecht-grundlagen.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/antikorruptionsgesetz-410v-massnahmensystem.md', 'fachliteratur', 4::smallint),
    ('pwc-worldwide-tax-summaries-kasachstan', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/investitionsrecht-zoll/investorenschutz-reform-generalstaatsanwalt-2025-2026.md', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/vertragsrecht-grundlagen/unidroit-principles-international-commercial-contracts.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-grundlagen/quellen/blockchain-iot-traceability-supply-chain.md', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/wasserrecht/gtai-neues-wassergesetzbuch-kasachstan.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/digitaler-kodex-255-viii.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/berufsorganisationen-kollegija-professioneller-rat.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/kpmg-kaukasus-ki-risikomanagement.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-grundlagen/quellen/pwc-halo-ey-helix.md', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/umweltrecht/pravsky-erweiterte-herstellerverantwortung-epr.md', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/ip-und-datenschutz-grundlagen/wipo-was-ist-geistiges-eigentum.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/auditgesetz-304i-grundstruktur.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/lizenzierung-zustaendige-behoerde-finanzministerium.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-grundlagen/quellen/kpmg-clara-audit-chat.md', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/agrarrecht-allgemein/kazakhinvest-foerderinstitutionen-baiterek-acc-kazagrofinance.md', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/streitbeilegung-investitionsschutz/aifc-court-rechtsgrundlage-und-praxis.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/landkodex-art144-staatliche-landkontrolle.md', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/ip-und-datenschutz-grundlagen/cross-border-data-transfers-white-case.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/korruptionsrisikoanalyse-erlass12.md', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/legal-funktion-und-grc/coso-erm-framework-risikomanagement.md', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/devisenrecht/mg-partner-devisenkontrolle-nichtresidenten.md', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/saatgut-sortenrecht/gcomsort-staatliche-sortenkommission.md', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/bodenrecht-agrarland/kursiv-media-tokajew-unterzeichnung-verbot-2021.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/datenschutzgesetz-94v.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/staatliche-audit-datenbank-opendata-egov.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/samruk-kazyna-governance-kodex.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/atameken-nationalkodex-2021.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/phytosanitaerzertifikat-export.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/nccg-nationalkodex-fachueberblick.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/investitionspraeferenzen-zustaendige-stelle.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/landkodex-uebersicht-aktuelle-fassung.md', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/legal-tech-ki-assistenten/retrieval-augmented-generation-grundlagen-aws.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-grundlagen/quellen/mindbridge-continuous-anomaly-detection.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/agraroekonomieplan-2026-2028.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-grundlagen/quellen/deloitte-tax-cms-deutschland.md', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/legal-funktion-und-grc/iso-37301-compliance-management-systeme.md', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/bodenrecht-agrarland/esplora-legal-foreign-ownership-rules-2026.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/subventionsregeln-aic-investitionsvorhaben-verfahren.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-grundlagen/quellen/iaasb-catalog-of-issues-v2-2025.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/agrarkreditkorporation-betrugsbekaempfung.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/ag-gesetz-art61-interne-revision.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/sonderbesteuerung-altes-recht-kapitel78.md', 'fachliteratur', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/auditorenregister-dfo-kz.md', 'fachliteratur', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/devisenrecht/halykbank-praxishinweise-devisenkontrolle.md', 'fachliteratur', 4::smallint),
    ('ey-kasachstan-project-office-juli-2026', 'praxisbeitrag', 4::smallint),
    ('audit/Audit/03-handelsketten-und-lieferantenaudits/D7-017_Leitlinie_für_Frisches_Obst_und_Gemüse.md', 'praxisbeitrag', 4::smallint),
    ('audit/Audit/03-handelsketten-und-lieferantenaudits/D7-018_Annual_Report_2024.md', 'praxisbeitrag', 4::smallint),
    ('pro1c-formular-300-00-2026', 'praxisbeitrag', 4::smallint),
    ('mybuh-kz-virt-sklad-2026-rus', 'praxisbeitrag', 4::smallint),
    ('dentons-global-tax-guide-kasachstan', 'praxisbeitrag', 4::smallint),
    ('moore-esutd-strafen-2026', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/umweltrecht/fao-schulungen-pestizidreduktion-kasachstan.md', 'praxisbeitrag', 4::smallint),
    ('formular-913-00-abgeschafft-2026', 'praxisbeitrag', 4::smallint),
    ('mybuh-nds-zuschlag-vereinbarung-minselkhoz-2025-rus-veraltet', 'praxisbeitrag', 4::smallint),
    ('mybuh-mwst-schwelle-2026', 'praxisbeitrag', 4::smallint),
    ('audit/Audit/03-handelsketten-und-lieferantenaudits/D7-023_Food_Safety_Auditor_Professional_Development_Framework_Stakeholder_Consultation.md', 'praxisbeitrag', 4::smallint),
    ('audit/Audit/02-esg-nachhaltigkeit-und-qualitaetsaudit/D4-030_Integrity_Report.md', 'praxisbeitrag', 4::smallint),
    ('kpmg-kz-tax-newsflash-2026-07', 'praxisbeitrag', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/pflichtpruefung-art5-unternehmenstypen.md', 'praxisbeitrag', 4::smallint),
    ('pro1c-snr-uebersicht-2026-rus', 'praxisbeitrag', 4::smallint),
    ('pro1c-formular-200-00-2026', 'praxisbeitrag', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/subventionsregeln-aic-monitoring-rueckforderung.md', 'praxisbeitrag', 4::smallint),
    ('mybuh-lpkh-kpn-kooperativ-vorschlag-2026-rus', 'praxisbeitrag', 4::smallint),
    ('osms-beitragssaetze-mybuh-2026', 'praxisbeitrag', 4::smallint),
    ('pro1c-esf-ncalayer-signatur-pflicht', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/investitionsrecht-zoll/kazlawreview-verfahrensluecke-zollbefreiung.md', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/bodenrecht-agrarland/kpmg-law-kasachstan-indirekte-beteiligung-unklarheit.md', 'praxisbeitrag', 4::smallint),
    ('world-bank-economic-update-kasachstan-2025', 'praxisbeitrag', 4::smallint),
    ('adb-kasachstan-fiskalreform-2026', 'praxisbeitrag', 4::smallint),
    ('audit/Audit/01-interne-revision-und-oeffentlicher-sektor/D2-035_Enhancing_Co-operation_Between_Internal_and_External_Auditors.md', 'praxisbeitrag', 4::smallint),
    ('consaltprofi-kameralkontrolle-2026', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/arbeitsrecht/eqonaq-registrierungspflicht-drei-werktage.md', 'praxisbeitrag', 4::smallint),
    ('1cbit-kz-import-export-uchet-2026-rus', 'praxisbeitrag', 4::smallint),
    ('iris-kz-art484-status-rus', 'praxisbeitrag', 4::smallint),
    ('pwc-ceo-survey-2026-kasachstan', 'praxisbeitrag', 4::smallint),
    ('uchet-esutd-shtrafy-2026', 'praxisbeitrag', 4::smallint),
    ('mybuh-khfh-weiterverkauf-fizlitsa-2022-rus-veraltet', 'praxisbeitrag', 4::smallint),
    ('mybuh-khfh-dokhod-2026-rus', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/antikorruption/uncac-un-konvention-gegen-korruption-struktur-und-ratifikation.md', 'praxisbeitrag', 4::smallint),
    ('mybuh-nds-befreiung-spk-lpkh-vorschlag-2026-rus', 'praxisbeitrag', 4::smallint),
    ('mybuh-too-vs-khfh-2026-rus', 'praxisbeitrag', 4::smallint),
    ('audit/Audit/01-interne-revision-und-oeffentlicher-sektor/D2-028_Interne_Revision_und_Risikomanagement_Empfehlungen_zum_Zusammenwirken_Positionsp.md', 'praxisbeitrag', 4::smallint),
    ('pro1c-kz-proslezhivaemost-sept2026-rus', 'praxisbeitrag', 4::smallint),
    ('pro1c-ip-our-progressiv-2026-rus', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/streitbeilegung-investitionsschutz/international-arbitration-centre-iac-aifc.md', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/vertragsrecht-grundlagen/contract-lifecycle-management-nutzen-thomson-reuters.md', 'praxisbeitrag', 4::smallint),
    ('pro1c-formular-910-00-2026', 'praxisbeitrag', 4::smallint),
    ('mybuh-snr-selkhoz-khfh-2026-rus', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/geistiges-eigentum/wcr-consulting-quellcode-hinterlegung-kazpatent.md', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/legal-tech-ki-assistenten/hallucination-free-stanford-studie-ki-rechtsassistenten.md', 'praxisbeitrag', 4::smallint),
    ('mybuh-nds-schwelle-2026-bestaetigung-rus', 'praxisbeitrag', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/staatliche-audit-datenbank-weitere-kammern.md', 'praxisbeitrag', 4::smallint),
    ('mybuh-khfh-our-formulare-2026-rus', 'praxisbeitrag', 4::smallint),
    ('kpmg-kz-tax-newsflash-2026-07-2', 'praxisbeitrag', 4::smallint),
    ('unicaselaw-budget-deficit-business-burden', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/datenschutzrecht/grata-international-datenschutzaufsicht-digitalministerium-meldepflicht.md', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/gesellschaftsrecht-registrierung/dos-immigration-too-registrierung-leitfaden.md', 'praxisbeitrag', 4::smallint),
    ('mybuh-formular-100-00-frist', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/ip-und-datenschutz-grundlagen/auftragsverarbeitungsvertraege-praxisanalyse-lawinsider.md', 'praxisbeitrag', 4::smallint),
    ('mybuh-privatvermoegen-ipn-2025-rus', 'praxisbeitrag', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/audit-kz-negativbefund-ki-stellungnahme.md', 'praxisbeitrag', 4::smallint),
    ('kpmg-kz-neue-steuermassnahmen-2026-09', 'praxisbeitrag', 4::smallint),
    ('mybuh-nds-zuschlag-konditerei-2025-rus-veraltet', 'praxisbeitrag', 4::smallint),
    ('kpmg-kz-tax-newsflash-uebersicht', 'praxisbeitrag', 4::smallint),
    ('uchet-kz-komissioner-oborot-rus', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/gesellschaftsrecht-registrierung/persoenliche-anwesenheit-gruender-ab-april-2026.md', 'praxisbeitrag', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/internationale-pruefungsstandards-kz-verbindlichkeit.md', 'praxisbeitrag', 4::smallint),
    ('oecd-tax-policy-review-kasachstan-2020', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/kartellrecht/oecd-pruefbericht-wettbewerbsrecht-kasachstan-november-2025.md', 'praxisbeitrag', 4::smallint),
    ('mybuh-ofd-liste-2026', 'praxisbeitrag', 4::smallint),
    ('moore-kasachstan-neuer-steuerkodex', 'praxisbeitrag', 4::smallint),
    ('pro1c-virtueller-lager-bestand', 'praxisbeitrag', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/kpmg-law-rechtsunsicherheit-mittelbare-beteiligung.md', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/legal-tech-ki-assistenten/rag-in-legal-tech-thomson-reuters.md', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/pflanzenschutz-lebensmittelsicherheit/tr-cu-021-2011-lebensmittelsicherheit-schmidt-schmidt.md', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/legal-tech-ki-assistenten/generative-ai-corporate-boards-harvard-forum.md', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/gesellschaftsrecht-registrierung/world-bank-business-ready-2025-kasachstan.md', 'praxisbeitrag', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/weltbank-rosc-bericht-kz-pruefungswesen.md', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/legal-funktion-und-grc/general-counsel-als-lawyer-statesman-heineman.md', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/pflanzenschutz-lebensmittelsicherheit/tr-cu-022-2011-kennzeichnung-schmidt-schmidt.md', 'praxisbeitrag', 4::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/steuerrecht-schnittstelle/mwst-satz-erhoehung-16-prozent-2026.md', 'praxisbeitrag', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/berufsorganisationen-palata-auditorov.md', 'praxisbeitrag', 4::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/staatlicher-rechnungspruefungsaudit-digitalisierung.md', 'internetquelle', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/eawu-aussenhandel/eastfruit-obst-beeren-export-kasachstan-2024.md', 'internetquelle', 5::smallint),
    ('profinance-kz-rechner', 'internetquelle', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/vertragsrecht-grundlagen/contract-and-commercial-management-cummins-buch.md', 'internetquelle', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/agrarrecht-allgemein/zakon-kz-komplexplan-agraroekonomie-2026-2028.md', 'internetquelle', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/agrarrecht-allgemein/kapital-kz-gesetzentwurf-bioproduktion-2024.md', 'internetquelle', 5::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/mindestanforderungen-pruefungsgesellschaften-2026.md', 'internetquelle', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/ip-und-datenschutz-grundlagen/european-data-protection-law-and-practice-ustaran-buch.md', 'internetquelle', 5::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/vap-weitere-feststellungen-2023-2025.md', 'internetquelle', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/pflanzenschutz-lebensmittelsicherheit/eastfruit-umstellung-bio-obst-gemuese-kasachstan.md', 'internetquelle', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/arbeitsrecht/auslaenderquote-2026-anhebung-auf-0-3-prozent.md', 'internetquelle', 5::smallint),
    ('calculators-kz-rechner', 'internetquelle', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/bodenrecht-agrarland/azattyq-ruhy-lazeika-indirekte-beteiligung.md', 'internetquelle', 5::smallint),
    ('prodengi-kz-rechner', 'internetquelle', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/legal-funktion-und-grc/running-legal-like-a-business-legal-operations-buch.md', 'internetquelle', 5::smallint),
    ('arqabuh-kz-rechner', 'internetquelle', 5::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/digitale-kontrollinstrumente-gosagro-jerinspectr.md', 'internetquelle', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/wasserrecht/inbusiness-uebergangsfrist-2027-genehmigungspflicht.md', 'internetquelle', 5::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/compliance-trennung-erlass112.md', 'internetquelle', 5::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/steuerreform-2026-neues-gesetzbuch.md', 'internetquelle', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/legal-funktion-und-grc/iso-31000-risikomanagement-grundsaetze.md', 'internetquelle', 5::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/moratorium-privatisierung-kasachstani.md', 'internetquelle', 5::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/lizenzierung-kvga-zustaendigkeitswechsel-2026.md', 'internetquelle', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/datenschutzrecht/habr-regulierung-personenbezogener-daten-kasachstan.md', 'internetquelle', 5::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/umgehungsrisiko-beteiligungserwerb-greenasia.md', 'internetquelle', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/arbeitsrecht/zakon-kz-irs-verfahrensaenderungen-2025.md', 'internetquelle', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/devisenrecht/habr-gruendererfahrung-zahlungen-too.md', 'internetquelle', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/antikorruption/knb-agentur-aufloesung-neuordnung-2025.md', 'internetquelle', 5::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/vap-bericht-2024-subventionen-hauptbefunde.md', 'internetquelle', 5::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/bio-kennzeichnung-gesetz-89-viii.md', 'internetquelle', 5::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/landverbot-2021-pachtstatistik-fachpresse.md', 'internetquelle', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/legal-tech-ki-assistenten/harvey-ai-praxiserfahrungen-g2-reviews.md', 'forum', 5::smallint),
    ('forum-zakon-kz-buchhalterforum', 'forum', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/kasachstan-recht/arbeitsrecht/forumsbeitrag-erfahrungsbericht-visum-arbeitserlaubnis-expat.md', 'forum', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/vertragsrecht-grundlagen/clm-software-auswahl-praxisdiskussion-g2.md', 'forum', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/legal-grundlagen/legal-funktion-und-grc/grc-plattformen-praxiserfahrungen-g2-reviews.md', 'forum', 5::smallint),
    ('audit/audit-kasachstan/04-luecken-und-fragen.md', 'internetrecherche', 5::smallint),
    ('audit/audit-kasachstan/05-fragen-pruefer.ru.md', 'internetrecherche', 5::smallint),
    ('audit/audit-fachliteratur/04-esg-nachhaltigkeit-und-qualitaetsaudit.md', 'internetrecherche', 5::smallint),
    ('kernwissen/handel-kommission-rohbefund.md', 'internetrecherche', 5::smallint),
    ('kernwissen/khfh-regime-rohbefund.md', 'internetrecherche', 5::smallint),
    ('audit/audit-kasachstan/02-quellenkarte.md', 'internetrecherche', 5::smallint),
    ('audit/audit-fachliteratur/06-digitalisierung-ausbildung-und-frameworks.md', 'internetrecherche', 5::smallint),
    ('audit/audit-fachliteratur/05-forensik-betrug-und-compliance-audit.md', 'internetrecherche', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/00_INDEX.md', 'internetrecherche', 5::smallint),
    ('audit/audit-fachliteratur/01-finanz-abschluss-und-steuerpruefung.md', 'internetrecherche', 5::smallint),
    ('audit/audit-fachliteratur/03-it-cybersecurity-und-ki-audit.md', 'internetrecherche', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/00_INDEX.md', 'internetrecherche', 5::smallint),
    ('audit/audit-kasachstan/01-suchbegriffe.md', 'internetrecherche', 5::smallint),
    ('audit/audit-fachliteratur/02-interne-revision-und-oeffentlicher-sektor.md', 'internetrecherche', 5::smallint),
    ('audit/audit-fachliteratur/_auftrag.md', 'internetrecherche', 5::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/00_INDEX.md', 'internetrecherche', 5::smallint),
    ('audit/audit-kasachstan/widerlegung/_auftrag.md', 'internetrecherche', 5::smallint),
    ('audit/audit-kasachstan/00-research-plan.md', 'internetrecherche', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Grundlagenwissen_laenderunabhaengig/README.md', 'internetrecherche', 5::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/it-sicherheit-beschluss-832-unbestaetigt.md', 'internetrecherche', 5::smallint),
    ('kernwissen/sanktionen-rohbefund.md', 'internetrecherche', 5::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/README.md', 'internetrecherche', 5::smallint),
    ('audit/Audit/damicon-audit-kb-grundlagen/00_INDEX.md', 'internetrecherche', 5::smallint),
    ('audit/audit-kasachstan/README.md', 'internetrecherche', 5::smallint),
    ('legal/Legal/WAMOCON_Legal_Wissensdatenbank_Kasachstan/README.md', 'internetrecherche', 5::smallint),
    ('audit/audit-kasachstan/rohfunde/_auftrag.md', 'internetrecherche', 5::smallint),
    ('audit/audit-fachliteratur/README.md', 'internetrecherche', 5::smallint),
    ('audit/Audit/damicon-audit-kb-grundlagen/README.md', 'internetrecherche', 5::smallint),
    ('audit/Audit/damicon-audit-kb-kasachstan/quellen/staatliche-audit-datenbank-ardfm.md', 'internetrecherche', 5::smallint)
  ) as v (quelle_id, art, stufe)
 where c.quelle_id = v.quelle_id
   and c.quellenart is null
   and coalesce(c.extra ->> 'quelle', '') <> 'upload';
